#!perl

# DATE
# VERSION

use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Any;

my $prefix = '/App/isbn/';
my $cli = Perinci::CmdLine::Any->new(
    url => "${prefix}isbn",
    log => 1,
    log_level => 'info',
);
$cli->run;

# ABSTRACT: Query book information by ISBN
# PODNAME:

=head1 SYNOPSIS

List installed drivers:

 % isbn -l

List all available drivers:

 % isbn -L

Search an ISBN using all installed drivers:

 % isbn 1860499058

Search an ISBN using specified driver(s):

 % isbn 1860499058 -d AmazonDE -d OpenLibrary -d Blackwell


=head1 SEE ALSO

L<WWW::Scraper::ISBN> and its various driver modules
C<WWW::Scraper::ISBN::*_Driver>.
